Repository janstenpickle/hotswap-ref, pull requests merged in 2021-06, with the labels that each got.

#7 Update sbt to 1.5.3
  project/build.properties
Labels: dependency-update

#8 Update sbt-tpolecat to 0.1.20
  project/plugins.sbt
Labels: dependency-update

#11 Update sbt to 1.5.4
  project/build.properties
Labels: dependency-update

#12 Use sbt-github-actions
  .github/release-drafter.yml
  .github/workflows/build.yaml
  .github/workflows/ci.yml
  .github/workflows/clean.yml
  build.sbt
  ci-release.sbt
  project/Dependencies.scala
  project/plugins.sbt
Labels: skip-changelog

#13 Add mima checks, fix mergify.yml
  .github/mergify.yml
  .mergify.yml
  build.sbt
  project/plugins.sbt
Labels: chore

#16 Unify build, workflows
  .github/workflows/ci.yml
  ci-release.sbt
Labels: skip-changelog

#15 Fix cancelation scopes for `access`
  modules/core/src/main/scala/io/janstenpickle/hotswapref/HotswapRef.scala
  modules/core/src/test/scala/io/janstenpickle/hotswapref/HotswapRefSpec.scala
Labels: bug
